http:
  routers:
    hello-router:
      rule: "PathPrefix(`/hello`)"
      service: hello-service
      entryPoints:
        - web
    beszel:
      # Doesnt work for now since the base path needs to be set on the beszel hub host
      rule: "PathPrefix(`/beszel`)"
      service: beszel
      entryPoints:
        - web
      middlewares:
        - beszel-stripprefix

  middlewares:
    beszel-stripprefix:
      stripPrefix:
        prefixes:
          - /beszel

  services:
    hello-service:
      loadBalancer:
        servers:
          - url: "http://httpbin.org"
    beszel:
      loadBalancer:
        servers:
          - url: "http://192.168.1.34:8090"
